databases:
  - name: task-manager-mongo
    databaseName: taskmanager
    user: taskuser
    region: ohio

services:
  - type: web
    name: task-manager-app
    runtime: docker
    region: ohio
    plan: free
    branch: main
    healthCheckPath: /health
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGODB_URI
        fromDatabase:
          name: task-manager-mongo
          property: connectionString
    buildCommand: ""
    startCommand: ""